name: farm_federate_flutter
description: Multimodal Crop Stress Detection frontend
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  image_picker: ^0.8.7+4
  path: ^1.8.2
  percent_indicator: ^4.2.2
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
